# Generated by Django 4.2.3 on 2023-08-03 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_messages', '0002_alter_message_recipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
